version: '3.8'

services:
  postgres:
    container_name: gestao_vagas
    image: postgres
    ports:
      - "5433:5434"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=XerecaAzeda123!
      - POSTGRES_DB=gestao_vagas